replicaCount: 1
deploymentName: simple-flask-app

image:
  repository: mrasap/flask
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8080


resources:
 limits:
  cpu: 200m
  memory: 512Mi
 requests:
  cpu: 100m
  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
