---

- hosts: k3s_cluster
  become: yes
  remote_user: root
  gather_facts: no
  roles:
    - role: prereq
    - role: download

- hosts: master
  become: yes
  remote_user: root
  gather_facts: no
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  remote_user: root
  gather_facts: no
  roles:
    - role: k3s/node